/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { SOLANA_LLM_ORACLE_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const CALLBACK_FROM_LLM_DISCRIMINATOR = new Uint8Array([
  64, 202, 209, 39, 156, 18, 216, 170,
]);

export function getCallbackFromLlmDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CALLBACK_FROM_LLM_DISCRIMINATOR,
  );
}

export type CallbackFromLlmInstruction<
  TProgram extends string = typeof SOLANA_LLM_ORACLE_PROGRAM_ADDRESS,
  TAccountPayer extends string | AccountMeta<string> =
    "oRcjdxYJn7k8ujkMuh3phZGLnuRZ4VF3s3TZt5NEttE",
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountInference extends string | AccountMeta<string> = string,
  TAccountProgram extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountInference extends string
        ? WritableAccount<TAccountInference>
        : TAccountInference,
      TAccountProgram extends string
        ? ReadonlyAccount<TAccountProgram>
        : TAccountProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CallbackFromLlmInstructionData = {
  discriminator: ReadonlyUint8Array;
  response: string;
};

export type CallbackFromLlmInstructionDataArgs = { response: string };

export function getCallbackFromLlmInstructionDataEncoder(): Encoder<CallbackFromLlmInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["response", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ]),
    (value) => ({ ...value, discriminator: CALLBACK_FROM_LLM_DISCRIMINATOR }),
  );
}

export function getCallbackFromLlmInstructionDataDecoder(): Decoder<CallbackFromLlmInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["response", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
  ]);
}

export function getCallbackFromLlmInstructionDataCodec(): Codec<
  CallbackFromLlmInstructionDataArgs,
  CallbackFromLlmInstructionData
> {
  return combineCodec(
    getCallbackFromLlmInstructionDataEncoder(),
    getCallbackFromLlmInstructionDataDecoder(),
  );
}

export type CallbackFromLlmAsyncInput<
  TAccountPayer extends string = string,
  TAccountConfig extends string = string,
  TAccountInference extends string = string,
  TAccountProgram extends string = string,
> = {
  payer?: TransactionSigner<TAccountPayer>;
  config?: Address<TAccountConfig>;
  inference: Address<TAccountInference>;
  program: Address<TAccountProgram>;
  response: CallbackFromLlmInstructionDataArgs["response"];
};

export async function getCallbackFromLlmInstructionAsync<
  TAccountPayer extends string,
  TAccountConfig extends string,
  TAccountInference extends string,
  TAccountProgram extends string,
  TProgramAddress extends Address = typeof SOLANA_LLM_ORACLE_PROGRAM_ADDRESS,
>(
  input: CallbackFromLlmAsyncInput<
    TAccountPayer,
    TAccountConfig,
    TAccountInference,
    TAccountProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  CallbackFromLlmInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountConfig,
    TAccountInference,
    TAccountProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SOLANA_LLM_ORACLE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    inference: { value: input.inference ?? null, isWritable: true },
    program: { value: input.program ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.payer.value) {
    accounts.payer.value =
      "oRcjdxYJn7k8ujkMuh3phZGLnuRZ4VF3s3TZt5NEttE" as Address<"oRcjdxYJn7k8ujkMuh3phZGLnuRZ4VF3s3TZt5NEttE">;
  }
  if (!accounts.config.value) {
    accounts.config.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([99, 111, 110, 102, 105, 103])),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.inference),
      getAccountMeta(accounts.program),
    ],
    data: getCallbackFromLlmInstructionDataEncoder().encode(
      args as CallbackFromLlmInstructionDataArgs,
    ),
    programAddress,
  } as CallbackFromLlmInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountConfig,
    TAccountInference,
    TAccountProgram
  >);
}

export type CallbackFromLlmInput<
  TAccountPayer extends string = string,
  TAccountConfig extends string = string,
  TAccountInference extends string = string,
  TAccountProgram extends string = string,
> = {
  payer?: TransactionSigner<TAccountPayer>;
  config: Address<TAccountConfig>;
  inference: Address<TAccountInference>;
  program: Address<TAccountProgram>;
  response: CallbackFromLlmInstructionDataArgs["response"];
};

export function getCallbackFromLlmInstruction<
  TAccountPayer extends string,
  TAccountConfig extends string,
  TAccountInference extends string,
  TAccountProgram extends string,
  TProgramAddress extends Address = typeof SOLANA_LLM_ORACLE_PROGRAM_ADDRESS,
>(
  input: CallbackFromLlmInput<
    TAccountPayer,
    TAccountConfig,
    TAccountInference,
    TAccountProgram
  >,
  config?: { programAddress?: TProgramAddress },
): CallbackFromLlmInstruction<
  TProgramAddress,
  TAccountPayer,
  TAccountConfig,
  TAccountInference,
  TAccountProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SOLANA_LLM_ORACLE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    payer: { value: input.payer ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    inference: { value: input.inference ?? null, isWritable: true },
    program: { value: input.program ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.payer.value) {
    accounts.payer.value =
      "oRcjdxYJn7k8ujkMuh3phZGLnuRZ4VF3s3TZt5NEttE" as Address<"oRcjdxYJn7k8ujkMuh3phZGLnuRZ4VF3s3TZt5NEttE">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.inference),
      getAccountMeta(accounts.program),
    ],
    data: getCallbackFromLlmInstructionDataEncoder().encode(
      args as CallbackFromLlmInstructionDataArgs,
    ),
    programAddress,
  } as CallbackFromLlmInstruction<
    TProgramAddress,
    TAccountPayer,
    TAccountConfig,
    TAccountInference,
    TAccountProgram
  >);
}

export type ParsedCallbackFromLlmInstruction<
  TProgram extends string = typeof SOLANA_LLM_ORACLE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    payer: TAccountMetas[0];
    config: TAccountMetas[1];
    inference: TAccountMetas[2];
    program: TAccountMetas[3];
  };
  data: CallbackFromLlmInstructionData;
};

export function parseCallbackFromLlmInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCallbackFromLlmInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      payer: getNextAccount(),
      config: getNextAccount(),
      inference: getNextAccount(),
      program: getNextAccount(),
    },
    data: getCallbackFromLlmInstructionDataDecoder().decode(instruction.data),
  };
}
