/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { SOLANA_LLM_ORACLE_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const DELEGATE_DISCRIMINATOR = new Uint8Array([
  90, 147, 75, 178, 85, 88, 4, 137,
]);

export function getDelegateDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(DELEGATE_DISCRIMINATOR);
}

export type DelegateInstruction<
  TProgram extends string = typeof SOLANA_LLM_ORACLE_PROGRAM_ADDRESS,
  TAccountUser extends string | AccountMeta<string> = string,
  TAccountChatContext extends string | AccountMeta<string> = string,
  TAccountBufferInference extends string | AccountMeta<string> = string,
  TAccountDelegationRecordInference extends string | AccountMeta<string> =
    string,
  TAccountDelegationMetadataInference extends string | AccountMeta<string> =
    string,
  TAccountInference extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TAccountOwnerProgram extends string | AccountMeta<string> =
    "LLM4VF4uxgbcrUdwF9rBh7MUEypURp8FurEdZLhZqed",
  TAccountDelegationProgram extends string | AccountMeta<string> =
    "DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountUser extends string
        ? WritableSignerAccount<TAccountUser> & AccountSignerMeta<TAccountUser>
        : TAccountUser,
      TAccountChatContext extends string
        ? ReadonlyAccount<TAccountChatContext>
        : TAccountChatContext,
      TAccountBufferInference extends string
        ? WritableAccount<TAccountBufferInference>
        : TAccountBufferInference,
      TAccountDelegationRecordInference extends string
        ? WritableAccount<TAccountDelegationRecordInference>
        : TAccountDelegationRecordInference,
      TAccountDelegationMetadataInference extends string
        ? WritableAccount<TAccountDelegationMetadataInference>
        : TAccountDelegationMetadataInference,
      TAccountInference extends string
        ? WritableAccount<TAccountInference>
        : TAccountInference,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      TAccountOwnerProgram extends string
        ? ReadonlyAccount<TAccountOwnerProgram>
        : TAccountOwnerProgram,
      TAccountDelegationProgram extends string
        ? ReadonlyAccount<TAccountDelegationProgram>
        : TAccountDelegationProgram,
      ...TRemainingAccounts,
    ]
  >;

export type DelegateInstructionData = { discriminator: ReadonlyUint8Array };

export type DelegateInstructionDataArgs = {};

export function getDelegateInstructionDataEncoder(): FixedSizeEncoder<DelegateInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: DELEGATE_DISCRIMINATOR }),
  );
}

export function getDelegateInstructionDataDecoder(): FixedSizeDecoder<DelegateInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getDelegateInstructionDataCodec(): FixedSizeCodec<
  DelegateInstructionDataArgs,
  DelegateInstructionData
> {
  return combineCodec(
    getDelegateInstructionDataEncoder(),
    getDelegateInstructionDataDecoder(),
  );
}

export type DelegateAsyncInput<
  TAccountUser extends string = string,
  TAccountChatContext extends string = string,
  TAccountBufferInference extends string = string,
  TAccountDelegationRecordInference extends string = string,
  TAccountDelegationMetadataInference extends string = string,
  TAccountInference extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountOwnerProgram extends string = string,
  TAccountDelegationProgram extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  chatContext: Address<TAccountChatContext>;
  bufferInference?: Address<TAccountBufferInference>;
  delegationRecordInference?: Address<TAccountDelegationRecordInference>;
  delegationMetadataInference?: Address<TAccountDelegationMetadataInference>;
  inference?: Address<TAccountInference>;
  systemProgram?: Address<TAccountSystemProgram>;
  ownerProgram?: Address<TAccountOwnerProgram>;
  delegationProgram?: Address<TAccountDelegationProgram>;
};

export async function getDelegateInstructionAsync<
  TAccountUser extends string,
  TAccountChatContext extends string,
  TAccountBufferInference extends string,
  TAccountDelegationRecordInference extends string,
  TAccountDelegationMetadataInference extends string,
  TAccountInference extends string,
  TAccountSystemProgram extends string,
  TAccountOwnerProgram extends string,
  TAccountDelegationProgram extends string,
  TProgramAddress extends Address = typeof SOLANA_LLM_ORACLE_PROGRAM_ADDRESS,
>(
  input: DelegateAsyncInput<
    TAccountUser,
    TAccountChatContext,
    TAccountBufferInference,
    TAccountDelegationRecordInference,
    TAccountDelegationMetadataInference,
    TAccountInference,
    TAccountSystemProgram,
    TAccountOwnerProgram,
    TAccountDelegationProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  DelegateInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountChatContext,
    TAccountBufferInference,
    TAccountDelegationRecordInference,
    TAccountDelegationMetadataInference,
    TAccountInference,
    TAccountSystemProgram,
    TAccountOwnerProgram,
    TAccountDelegationProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SOLANA_LLM_ORACLE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    chatContext: { value: input.chatContext ?? null, isWritable: false },
    bufferInference: { value: input.bufferInference ?? null, isWritable: true },
    delegationRecordInference: {
      value: input.delegationRecordInference ?? null,
      isWritable: true,
    },
    delegationMetadataInference: {
      value: input.delegationMetadataInference ?? null,
      isWritable: true,
    },
    inference: { value: input.inference ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    ownerProgram: { value: input.ownerProgram ?? null, isWritable: false },
    delegationProgram: {
      value: input.delegationProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.inference.value) {
    accounts.inference.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([105, 110, 102, 101, 114, 101, 110, 99, 101]),
        ),
        getAddressEncoder().encode(expectAddress(accounts.user.value)),
        getAddressEncoder().encode(expectAddress(accounts.chatContext.value)),
      ],
    });
  }
  if (!accounts.bufferInference.value) {
    accounts.bufferInference.value = await getProgramDerivedAddress({
      programAddress:
        "LLM4VF4uxgbcrUdwF9rBh7MUEypURp8FurEdZLhZqed" as Address<"LLM4VF4uxgbcrUdwF9rBh7MUEypURp8FurEdZLhZqed">,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([98, 117, 102, 102, 101, 114])),
        getAddressEncoder().encode(expectAddress(accounts.inference.value)),
      ],
    });
  }
  if (!accounts.delegationRecordInference.value) {
    accounts.delegationRecordInference.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([100, 101, 108, 101, 103, 97, 116, 105, 111, 110]),
        ),
        getAddressEncoder().encode(expectAddress(accounts.inference.value)),
      ],
    });
  }
  if (!accounts.delegationMetadataInference.value) {
    accounts.delegationMetadataInference.value = await getProgramDerivedAddress(
      {
        programAddress,
        seeds: [
          getBytesEncoder().encode(
            new Uint8Array([
              100, 101, 108, 101, 103, 97, 116, 105, 111, 110, 45, 109, 101,
              116, 97, 100, 97, 116, 97,
            ]),
          ),
          getAddressEncoder().encode(expectAddress(accounts.inference.value)),
        ],
      },
    );
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.ownerProgram.value) {
    accounts.ownerProgram.value =
      "LLM4VF4uxgbcrUdwF9rBh7MUEypURp8FurEdZLhZqed" as Address<"LLM4VF4uxgbcrUdwF9rBh7MUEypURp8FurEdZLhZqed">;
  }
  if (!accounts.delegationProgram.value) {
    accounts.delegationProgram.value =
      "DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh" as Address<"DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.chatContext),
      getAccountMeta(accounts.bufferInference),
      getAccountMeta(accounts.delegationRecordInference),
      getAccountMeta(accounts.delegationMetadataInference),
      getAccountMeta(accounts.inference),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.ownerProgram),
      getAccountMeta(accounts.delegationProgram),
    ],
    data: getDelegateInstructionDataEncoder().encode({}),
    programAddress,
  } as DelegateInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountChatContext,
    TAccountBufferInference,
    TAccountDelegationRecordInference,
    TAccountDelegationMetadataInference,
    TAccountInference,
    TAccountSystemProgram,
    TAccountOwnerProgram,
    TAccountDelegationProgram
  >);
}

export type DelegateInput<
  TAccountUser extends string = string,
  TAccountChatContext extends string = string,
  TAccountBufferInference extends string = string,
  TAccountDelegationRecordInference extends string = string,
  TAccountDelegationMetadataInference extends string = string,
  TAccountInference extends string = string,
  TAccountSystemProgram extends string = string,
  TAccountOwnerProgram extends string = string,
  TAccountDelegationProgram extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  chatContext: Address<TAccountChatContext>;
  bufferInference: Address<TAccountBufferInference>;
  delegationRecordInference: Address<TAccountDelegationRecordInference>;
  delegationMetadataInference: Address<TAccountDelegationMetadataInference>;
  inference: Address<TAccountInference>;
  systemProgram?: Address<TAccountSystemProgram>;
  ownerProgram?: Address<TAccountOwnerProgram>;
  delegationProgram?: Address<TAccountDelegationProgram>;
};

export function getDelegateInstruction<
  TAccountUser extends string,
  TAccountChatContext extends string,
  TAccountBufferInference extends string,
  TAccountDelegationRecordInference extends string,
  TAccountDelegationMetadataInference extends string,
  TAccountInference extends string,
  TAccountSystemProgram extends string,
  TAccountOwnerProgram extends string,
  TAccountDelegationProgram extends string,
  TProgramAddress extends Address = typeof SOLANA_LLM_ORACLE_PROGRAM_ADDRESS,
>(
  input: DelegateInput<
    TAccountUser,
    TAccountChatContext,
    TAccountBufferInference,
    TAccountDelegationRecordInference,
    TAccountDelegationMetadataInference,
    TAccountInference,
    TAccountSystemProgram,
    TAccountOwnerProgram,
    TAccountDelegationProgram
  >,
  config?: { programAddress?: TProgramAddress },
): DelegateInstruction<
  TProgramAddress,
  TAccountUser,
  TAccountChatContext,
  TAccountBufferInference,
  TAccountDelegationRecordInference,
  TAccountDelegationMetadataInference,
  TAccountInference,
  TAccountSystemProgram,
  TAccountOwnerProgram,
  TAccountDelegationProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SOLANA_LLM_ORACLE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    chatContext: { value: input.chatContext ?? null, isWritable: false },
    bufferInference: { value: input.bufferInference ?? null, isWritable: true },
    delegationRecordInference: {
      value: input.delegationRecordInference ?? null,
      isWritable: true,
    },
    delegationMetadataInference: {
      value: input.delegationMetadataInference ?? null,
      isWritable: true,
    },
    inference: { value: input.inference ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
    ownerProgram: { value: input.ownerProgram ?? null, isWritable: false },
    delegationProgram: {
      value: input.delegationProgram ?? null,
      isWritable: false,
    },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }
  if (!accounts.ownerProgram.value) {
    accounts.ownerProgram.value =
      "LLM4VF4uxgbcrUdwF9rBh7MUEypURp8FurEdZLhZqed" as Address<"LLM4VF4uxgbcrUdwF9rBh7MUEypURp8FurEdZLhZqed">;
  }
  if (!accounts.delegationProgram.value) {
    accounts.delegationProgram.value =
      "DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh" as Address<"DELeGGvXpWV2fqJUhqcF5ZSYMS4JTLjteaAMARRSaeSh">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.chatContext),
      getAccountMeta(accounts.bufferInference),
      getAccountMeta(accounts.delegationRecordInference),
      getAccountMeta(accounts.delegationMetadataInference),
      getAccountMeta(accounts.inference),
      getAccountMeta(accounts.systemProgram),
      getAccountMeta(accounts.ownerProgram),
      getAccountMeta(accounts.delegationProgram),
    ],
    data: getDelegateInstructionDataEncoder().encode({}),
    programAddress,
  } as DelegateInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountChatContext,
    TAccountBufferInference,
    TAccountDelegationRecordInference,
    TAccountDelegationMetadataInference,
    TAccountInference,
    TAccountSystemProgram,
    TAccountOwnerProgram,
    TAccountDelegationProgram
  >);
}

export type ParsedDelegateInstruction<
  TProgram extends string = typeof SOLANA_LLM_ORACLE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    user: TAccountMetas[0];
    chatContext: TAccountMetas[1];
    bufferInference: TAccountMetas[2];
    delegationRecordInference: TAccountMetas[3];
    delegationMetadataInference: TAccountMetas[4];
    inference: TAccountMetas[5];
    systemProgram: TAccountMetas[6];
    ownerProgram: TAccountMetas[7];
    delegationProgram: TAccountMetas[8];
  };
  data: DelegateInstructionData;
};

export function parseDelegateInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedDelegateInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 9) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      user: getNextAccount(),
      chatContext: getNextAccount(),
      bufferInference: getNextAccount(),
      delegationRecordInference: getNextAccount(),
      delegationMetadataInference: getNextAccount(),
      inference: getNextAccount(),
      systemProgram: getNextAccount(),
      ownerProgram: getNextAccount(),
      delegationProgram: getNextAccount(),
    },
    data: getDelegateInstructionDataDecoder().decode(instruction.data),
  };
}
