/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  type ParsedCallbackFromLlmInstruction,
  type ParsedCallbackTestInstruction,
  type ParsedCreateChatInstruction,
  type ParsedCreateLlmInferenceInstruction,
  type ParsedDelegateInstruction,
  type ParsedInitializeInstruction,
  type ParsedProcessUndelegationInstruction,
} from "../instructions";

export const SOLANA_LLM_ORACLE_PROGRAM_ADDRESS =
  "LLM4VF4uxgbcrUdwF9rBh7MUEypURp8FurEdZLhZqed" as Address<"LLM4VF4uxgbcrUdwF9rBh7MUEypURp8FurEdZLhZqed">;

export enum SolanaLlmOracleAccount {
  ChatContext,
  Config,
  Inference,
}

export function identifySolanaLlmOracleAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): SolanaLlmOracleAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([28, 122, 31, 214, 78, 136, 26, 215]),
      ),
      0,
    )
  ) {
    return SolanaLlmOracleAccount.ChatContext;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([155, 12, 170, 224, 30, 250, 204, 130]),
      ),
      0,
    )
  ) {
    return SolanaLlmOracleAccount.Config;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([212, 88, 92, 102, 232, 184, 55, 139]),
      ),
      0,
    )
  ) {
    return SolanaLlmOracleAccount.Inference;
  }
  throw new Error(
    "The provided account could not be identified as a solanaLlmOracle account.",
  );
}

export enum SolanaLlmOracleInstruction {
  CallbackFromLlm,
  CallbackTest,
  CreateChat,
  CreateLlmInference,
  Delegate,
  Initialize,
  ProcessUndelegation,
}

export function identifySolanaLlmOracleInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): SolanaLlmOracleInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([64, 202, 209, 39, 156, 18, 216, 170]),
      ),
      0,
    )
  ) {
    return SolanaLlmOracleInstruction.CallbackFromLlm;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([196, 61, 185, 224, 30, 229, 25, 52]),
      ),
      0,
    )
  ) {
    return SolanaLlmOracleInstruction.CallbackTest;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([133, 186, 254, 72, 143, 178, 221, 28]),
      ),
      0,
    )
  ) {
    return SolanaLlmOracleInstruction.CreateChat;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([137, 172, 23, 129, 50, 162, 3, 252]),
      ),
      0,
    )
  ) {
    return SolanaLlmOracleInstruction.CreateLlmInference;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([90, 147, 75, 178, 85, 88, 4, 137]),
      ),
      0,
    )
  ) {
    return SolanaLlmOracleInstruction.Delegate;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([175, 175, 109, 31, 13, 152, 155, 237]),
      ),
      0,
    )
  ) {
    return SolanaLlmOracleInstruction.Initialize;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([196, 28, 41, 206, 48, 37, 51, 167]),
      ),
      0,
    )
  ) {
    return SolanaLlmOracleInstruction.ProcessUndelegation;
  }
  throw new Error(
    "The provided instruction could not be identified as a solanaLlmOracle instruction.",
  );
}

export type ParsedSolanaLlmOracleInstruction<
  TProgram extends string = "LLM4VF4uxgbcrUdwF9rBh7MUEypURp8FurEdZLhZqed",
> =
  | ({
      instructionType: SolanaLlmOracleInstruction.CallbackFromLlm;
    } & ParsedCallbackFromLlmInstruction<TProgram>)
  | ({
      instructionType: SolanaLlmOracleInstruction.CallbackTest;
    } & ParsedCallbackTestInstruction<TProgram>)
  | ({
      instructionType: SolanaLlmOracleInstruction.CreateChat;
    } & ParsedCreateChatInstruction<TProgram>)
  | ({
      instructionType: SolanaLlmOracleInstruction.CreateLlmInference;
    } & ParsedCreateLlmInferenceInstruction<TProgram>)
  | ({
      instructionType: SolanaLlmOracleInstruction.Delegate;
    } & ParsedDelegateInstruction<TProgram>)
  | ({
      instructionType: SolanaLlmOracleInstruction.Initialize;
    } & ParsedInitializeInstruction<TProgram>)
  | ({
      instructionType: SolanaLlmOracleInstruction.ProcessUndelegation;
    } & ParsedProcessUndelegationInstruction<TProgram>);
