/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getAccountMetaDecoder,
  getAccountMetaEncoder,
  type AccountMeta,
  type AccountMetaArgs,
} from "../types";

export const INFERENCE_DISCRIMINATOR = new Uint8Array([
  212, 88, 92, 102, 232, 184, 55, 139,
]);

export function getInferenceDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(INFERENCE_DISCRIMINATOR);
}

export type Inference = {
  discriminator: ReadonlyUint8Array;
  chatContext: Address;
  user: Address;
  text: string;
  callbackProgramId: Address;
  callbackDiscriminator: ReadonlyUint8Array;
  callbackAccountMetas: Array<AccountMeta>;
  isProcessed: boolean;
};

export type InferenceArgs = {
  chatContext: Address;
  user: Address;
  text: string;
  callbackProgramId: Address;
  callbackDiscriminator: ReadonlyUint8Array;
  callbackAccountMetas: Array<AccountMetaArgs>;
  isProcessed: boolean;
};

/** Gets the encoder for {@link InferenceArgs} account data. */
export function getInferenceEncoder(): Encoder<InferenceArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["chatContext", getAddressEncoder()],
      ["user", getAddressEncoder()],
      ["text", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
      ["callbackProgramId", getAddressEncoder()],
      ["callbackDiscriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["callbackAccountMetas", getArrayEncoder(getAccountMetaEncoder())],
      ["isProcessed", getBooleanEncoder()],
    ]),
    (value) => ({ ...value, discriminator: INFERENCE_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link Inference} account data. */
export function getInferenceDecoder(): Decoder<Inference> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["chatContext", getAddressDecoder()],
    ["user", getAddressDecoder()],
    ["text", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ["callbackProgramId", getAddressDecoder()],
    ["callbackDiscriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["callbackAccountMetas", getArrayDecoder(getAccountMetaDecoder())],
    ["isProcessed", getBooleanDecoder()],
  ]);
}

/** Gets the codec for {@link Inference} account data. */
export function getInferenceCodec(): Codec<InferenceArgs, Inference> {
  return combineCodec(getInferenceEncoder(), getInferenceDecoder());
}

export function decodeInference<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<Inference, TAddress>;
export function decodeInference<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<Inference, TAddress>;
export function decodeInference<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<Inference, TAddress> | MaybeAccount<Inference, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getInferenceDecoder(),
  );
}

export async function fetchInference<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<Inference, TAddress>> {
  const maybeAccount = await fetchMaybeInference(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeInference<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<Inference, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeInference(maybeAccount);
}

export async function fetchAllInference(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<Inference>[]> {
  const maybeAccounts = await fetchAllMaybeInference(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeInference(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<Inference>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeInference(maybeAccount));
}
