/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  type ParsedAiInferenceInstruction,
  type ParsedCallbackFromAiInstruction,
  type ParsedInitializeInstruction,
} from "../instructions";

export const CHAT_AGENT_PROGRAM_ADDRESS =
  "oTEBPw8FxjnpDhPtiC5QzfNMcDn1n4AJ1i5NidvQecf" as Address<"oTEBPw8FxjnpDhPtiC5QzfNMcDn1n4AJ1i5NidvQecf">;

export enum ChatAgentAccount {
  ChatContext,
  Config,
}

export function identifyChatAgentAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): ChatAgentAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([28, 122, 31, 214, 78, 136, 26, 215]),
      ),
      0,
    )
  ) {
    return ChatAgentAccount.ChatContext;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([155, 12, 170, 224, 30, 250, 204, 130]),
      ),
      0,
    )
  ) {
    return ChatAgentAccount.Config;
  }
  throw new Error(
    "The provided account could not be identified as a chatAgent account.",
  );
}

export enum ChatAgentInstruction {
  AiInference,
  CallbackFromAi,
  Initialize,
}

export function identifyChatAgentInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): ChatAgentInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([139, 217, 84, 45, 253, 148, 169, 10]),
      ),
      0,
    )
  ) {
    return ChatAgentInstruction.AiInference;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([153, 28, 39, 253, 98, 30, 162, 68]),
      ),
      0,
    )
  ) {
    return ChatAgentInstruction.CallbackFromAi;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([175, 175, 109, 31, 13, 152, 155, 237]),
      ),
      0,
    )
  ) {
    return ChatAgentInstruction.Initialize;
  }
  throw new Error(
    "The provided instruction could not be identified as a chatAgent instruction.",
  );
}

export type ParsedChatAgentInstruction<
  TProgram extends string = "oTEBPw8FxjnpDhPtiC5QzfNMcDn1n4AJ1i5NidvQecf",
> =
  | ({
      instructionType: ChatAgentInstruction.AiInference;
    } & ParsedAiInferenceInstruction<TProgram>)
  | ({
      instructionType: ChatAgentInstruction.CallbackFromAi;
    } & ParsedCallbackFromAiInstruction<TProgram>)
  | ({
      instructionType: ChatAgentInstruction.Initialize;
    } & ParsedInitializeInstruction<TProgram>);
