/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from "@solana/kit";
import { CHAT_AGENT_PROGRAM_ADDRESS } from "../programs";

/** InvalidOracleIdentity: Invalid account or oracle sent the callback! */
export const CHAT_AGENT_ERROR__INVALID_ORACLE_IDENTITY = 0x1770; // 6000

export type ChatAgentError = typeof CHAT_AGENT_ERROR__INVALID_ORACLE_IDENTITY;

let chatAgentErrorMessages: Record<ChatAgentError, string> | undefined;
if (process.env.NODE_ENV !== "production") {
  chatAgentErrorMessages = {
    [CHAT_AGENT_ERROR__INVALID_ORACLE_IDENTITY]: `Invalid account or oracle sent the callback!`,
  };
}

export function getChatAgentErrorMessage(code: ChatAgentError): string {
  if (process.env.NODE_ENV !== "production") {
    return (chatAgentErrorMessages as Record<ChatAgentError, string>)[code];
  }

  return "Error message not available in production bundles.";
}

export function isChatAgentError<TProgramErrorCode extends ChatAgentError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode,
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    CHAT_AGENT_PROGRAM_ADDRESS,
    code,
  );
}
