/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getStructDecoder,
  getStructEncoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type AccountMeta = {
  pubkey: Address;
  isSigner: boolean;
  isWritable: boolean;
};

export type AccountMetaArgs = AccountMeta;

export function getAccountMetaEncoder(): FixedSizeEncoder<AccountMetaArgs> {
  return getStructEncoder([
    ["pubkey", getAddressEncoder()],
    ["isSigner", getBooleanEncoder()],
    ["isWritable", getBooleanEncoder()],
  ]);
}

export function getAccountMetaDecoder(): FixedSizeDecoder<AccountMeta> {
  return getStructDecoder([
    ["pubkey", getAddressDecoder()],
    ["isSigner", getBooleanDecoder()],
    ["isWritable", getBooleanDecoder()],
  ]);
}

export function getAccountMetaCodec(): FixedSizeCodec<
  AccountMetaArgs,
  AccountMeta
> {
  return combineCodec(getAccountMetaEncoder(), getAccountMetaDecoder());
}
