/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type AccountMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import { SOLANA_LLM_ORACLE_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const CALLBACK_TEST_DISCRIMINATOR = new Uint8Array([
  196, 61, 185, 224, 30, 229, 25, 52,
]);

export function getCallbackTestDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CALLBACK_TEST_DISCRIMINATOR,
  );
}

export type CallbackTestInstruction<
  TProgram extends string = typeof SOLANA_LLM_ORACLE_PROGRAM_ADDRESS,
  TAccountConfig extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      ...TRemainingAccounts,
    ]
  >;

export type CallbackTestInstructionData = {
  discriminator: ReadonlyUint8Array;
  response: string;
};

export type CallbackTestInstructionDataArgs = { response: string };

export function getCallbackTestInstructionDataEncoder(): Encoder<CallbackTestInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["response", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ]),
    (value) => ({ ...value, discriminator: CALLBACK_TEST_DISCRIMINATOR }),
  );
}

export function getCallbackTestInstructionDataDecoder(): Decoder<CallbackTestInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["response", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
  ]);
}

export function getCallbackTestInstructionDataCodec(): Codec<
  CallbackTestInstructionDataArgs,
  CallbackTestInstructionData
> {
  return combineCodec(
    getCallbackTestInstructionDataEncoder(),
    getCallbackTestInstructionDataDecoder(),
  );
}

export type CallbackTestAsyncInput<TAccountConfig extends string = string> = {
  config?: Address<TAccountConfig>;
  response: CallbackTestInstructionDataArgs["response"];
};

export async function getCallbackTestInstructionAsync<
  TAccountConfig extends string,
  TProgramAddress extends Address = typeof SOLANA_LLM_ORACLE_PROGRAM_ADDRESS,
>(
  input: CallbackTestAsyncInput<TAccountConfig>,
  config?: { programAddress?: TProgramAddress },
): Promise<CallbackTestInstruction<TProgramAddress, TAccountConfig>> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SOLANA_LLM_ORACLE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([99, 111, 110, 102, 105, 103])),
      ],
    });
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [getAccountMeta(accounts.config)],
    data: getCallbackTestInstructionDataEncoder().encode(
      args as CallbackTestInstructionDataArgs,
    ),
    programAddress,
  } as CallbackTestInstruction<TProgramAddress, TAccountConfig>);
}

export type CallbackTestInput<TAccountConfig extends string = string> = {
  config: Address<TAccountConfig>;
  response: CallbackTestInstructionDataArgs["response"];
};

export function getCallbackTestInstruction<
  TAccountConfig extends string,
  TProgramAddress extends Address = typeof SOLANA_LLM_ORACLE_PROGRAM_ADDRESS,
>(
  input: CallbackTestInput<TAccountConfig>,
  config?: { programAddress?: TProgramAddress },
): CallbackTestInstruction<TProgramAddress, TAccountConfig> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SOLANA_LLM_ORACLE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    config: { value: input.config ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [getAccountMeta(accounts.config)],
    data: getCallbackTestInstructionDataEncoder().encode(
      args as CallbackTestInstructionDataArgs,
    ),
    programAddress,
  } as CallbackTestInstruction<TProgramAddress, TAccountConfig>);
}

export type ParsedCallbackTestInstruction<
  TProgram extends string = typeof SOLANA_LLM_ORACLE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    config: TAccountMetas[0];
  };
  data: CallbackTestInstructionData;
};

export function parseCallbackTestInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCallbackTestInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 1) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: { config: getNextAccount() },
    data: getCallbackTestInstructionDataDecoder().decode(instruction.data),
  };
}
