/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU8Decoder,
  getU8Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { SOLANA_LLM_ORACLE_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  expectSome,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const CREATE_CHAT_DISCRIMINATOR = new Uint8Array([
  133, 186, 254, 72, 143, 178, 221, 28,
]);

export function getCreateChatDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(CREATE_CHAT_DISCRIMINATOR);
}

export type CreateChatInstruction<
  TProgram extends string = typeof SOLANA_LLM_ORACLE_PROGRAM_ADDRESS,
  TAccountUser extends string | AccountMeta<string> = string,
  TAccountChatContext extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountUser extends string
        ? WritableSignerAccount<TAccountUser> & AccountSignerMeta<TAccountUser>
        : TAccountUser,
      TAccountChatContext extends string
        ? WritableAccount<TAccountChatContext>
        : TAccountChatContext,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CreateChatInstructionData = {
  discriminator: ReadonlyUint8Array;
  text: string;
  seed: number;
};

export type CreateChatInstructionDataArgs = { text: string; seed: number };

export function getCreateChatInstructionDataEncoder(): Encoder<CreateChatInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["text", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
      ["seed", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: CREATE_CHAT_DISCRIMINATOR }),
  );
}

export function getCreateChatInstructionDataDecoder(): Decoder<CreateChatInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["text", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ["seed", getU8Decoder()],
  ]);
}

export function getCreateChatInstructionDataCodec(): Codec<
  CreateChatInstructionDataArgs,
  CreateChatInstructionData
> {
  return combineCodec(
    getCreateChatInstructionDataEncoder(),
    getCreateChatInstructionDataDecoder(),
  );
}

export type CreateChatAsyncInput<
  TAccountUser extends string = string,
  TAccountChatContext extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  chatContext?: Address<TAccountChatContext>;
  systemProgram?: Address<TAccountSystemProgram>;
  text: CreateChatInstructionDataArgs["text"];
  seed: CreateChatInstructionDataArgs["seed"];
};

export async function getCreateChatInstructionAsync<
  TAccountUser extends string,
  TAccountChatContext extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof SOLANA_LLM_ORACLE_PROGRAM_ADDRESS,
>(
  input: CreateChatAsyncInput<
    TAccountUser,
    TAccountChatContext,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  CreateChatInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountChatContext,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SOLANA_LLM_ORACLE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    chatContext: { value: input.chatContext ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.chatContext.value) {
    accounts.chatContext.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([
            99, 104, 97, 116, 95, 99, 111, 110, 116, 101, 120, 116,
          ]),
        ),
        getAddressEncoder().encode(expectAddress(accounts.user.value)),
        getU8Encoder().encode(expectSome(args.seed)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.chatContext),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCreateChatInstructionDataEncoder().encode(
      args as CreateChatInstructionDataArgs,
    ),
    programAddress,
  } as CreateChatInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountChatContext,
    TAccountSystemProgram
  >);
}

export type CreateChatInput<
  TAccountUser extends string = string,
  TAccountChatContext extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  chatContext: Address<TAccountChatContext>;
  systemProgram?: Address<TAccountSystemProgram>;
  text: CreateChatInstructionDataArgs["text"];
  seed: CreateChatInstructionDataArgs["seed"];
};

export function getCreateChatInstruction<
  TAccountUser extends string,
  TAccountChatContext extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof SOLANA_LLM_ORACLE_PROGRAM_ADDRESS,
>(
  input: CreateChatInput<
    TAccountUser,
    TAccountChatContext,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): CreateChatInstruction<
  TProgramAddress,
  TAccountUser,
  TAccountChatContext,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SOLANA_LLM_ORACLE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    chatContext: { value: input.chatContext ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.chatContext),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCreateChatInstructionDataEncoder().encode(
      args as CreateChatInstructionDataArgs,
    ),
    programAddress,
  } as CreateChatInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountChatContext,
    TAccountSystemProgram
  >);
}

export type ParsedCreateChatInstruction<
  TProgram extends string = typeof SOLANA_LLM_ORACLE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    user: TAccountMetas[0];
    chatContext: TAccountMetas[1];
    systemProgram: TAccountMetas[2];
  };
  data: CreateChatInstructionData;
};

export function parseCreateChatInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCreateChatInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      user: getNextAccount(),
      chatContext: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getCreateChatInstructionDataDecoder().decode(instruction.data),
  };
}
