/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type Option,
  type OptionOrNullable,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { SOLANA_LLM_ORACLE_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";
import {
  getAccountMetaDecoder,
  getAccountMetaEncoder,
  type AccountMeta,
  type AccountMetaArgs,
} from "../types";

export const CREATE_LLM_INFERENCE_DISCRIMINATOR = new Uint8Array([
  137, 172, 23, 129, 50, 162, 3, 252,
]);

export function getCreateLlmInferenceDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CREATE_LLM_INFERENCE_DISCRIMINATOR,
  );
}

export type CreateLlmInferenceInstruction<
  TProgram extends string = typeof SOLANA_LLM_ORACLE_PROGRAM_ADDRESS,
  TAccountUser extends string | AccountMeta<string> = string,
  TAccountChatContext extends string | AccountMeta<string> = string,
  TAccountInference extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountUser extends string
        ? WritableSignerAccount<TAccountUser> & AccountSignerMeta<TAccountUser>
        : TAccountUser,
      TAccountChatContext extends string
        ? ReadonlyAccount<TAccountChatContext>
        : TAccountChatContext,
      TAccountInference extends string
        ? WritableAccount<TAccountInference>
        : TAccountInference,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CreateLlmInferenceInstructionData = {
  discriminator: ReadonlyUint8Array;
  text: string;
  callbackProgramId: Address;
  callbackDiscriminator: ReadonlyUint8Array;
  accountMetas: Option<Array<AccountMeta>>;
};

export type CreateLlmInferenceInstructionDataArgs = {
  text: string;
  callbackProgramId: Address;
  callbackDiscriminator: ReadonlyUint8Array;
  accountMetas: OptionOrNullable<Array<AccountMetaArgs>>;
};

export function getCreateLlmInferenceInstructionDataEncoder(): Encoder<CreateLlmInferenceInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["text", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
      ["callbackProgramId", getAddressEncoder()],
      ["callbackDiscriminator", fixEncoderSize(getBytesEncoder(), 8)],
      [
        "accountMetas",
        getOptionEncoder(getArrayEncoder(getAccountMetaEncoder())),
      ],
    ]),
    (value) => ({
      ...value,
      discriminator: CREATE_LLM_INFERENCE_DISCRIMINATOR,
    }),
  );
}

export function getCreateLlmInferenceInstructionDataDecoder(): Decoder<CreateLlmInferenceInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["text", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ["callbackProgramId", getAddressDecoder()],
    ["callbackDiscriminator", fixDecoderSize(getBytesDecoder(), 8)],
    [
      "accountMetas",
      getOptionDecoder(getArrayDecoder(getAccountMetaDecoder())),
    ],
  ]);
}

export function getCreateLlmInferenceInstructionDataCodec(): Codec<
  CreateLlmInferenceInstructionDataArgs,
  CreateLlmInferenceInstructionData
> {
  return combineCodec(
    getCreateLlmInferenceInstructionDataEncoder(),
    getCreateLlmInferenceInstructionDataDecoder(),
  );
}

export type CreateLlmInferenceAsyncInput<
  TAccountUser extends string = string,
  TAccountChatContext extends string = string,
  TAccountInference extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  chatContext: Address<TAccountChatContext>;
  inference?: Address<TAccountInference>;
  systemProgram?: Address<TAccountSystemProgram>;
  text: CreateLlmInferenceInstructionDataArgs["text"];
  callbackProgramId: CreateLlmInferenceInstructionDataArgs["callbackProgramId"];
  callbackDiscriminator: CreateLlmInferenceInstructionDataArgs["callbackDiscriminator"];
  accountMetas: CreateLlmInferenceInstructionDataArgs["accountMetas"];
};

export async function getCreateLlmInferenceInstructionAsync<
  TAccountUser extends string,
  TAccountChatContext extends string,
  TAccountInference extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof SOLANA_LLM_ORACLE_PROGRAM_ADDRESS,
>(
  input: CreateLlmInferenceAsyncInput<
    TAccountUser,
    TAccountChatContext,
    TAccountInference,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  CreateLlmInferenceInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountChatContext,
    TAccountInference,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SOLANA_LLM_ORACLE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    chatContext: { value: input.chatContext ?? null, isWritable: false },
    inference: { value: input.inference ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.inference.value) {
    accounts.inference.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([105, 110, 102, 101, 114, 101, 110, 99, 101]),
        ),
        getAddressEncoder().encode(expectAddress(accounts.user.value)),
        getAddressEncoder().encode(expectAddress(accounts.chatContext.value)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.chatContext),
      getAccountMeta(accounts.inference),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCreateLlmInferenceInstructionDataEncoder().encode(
      args as CreateLlmInferenceInstructionDataArgs,
    ),
    programAddress,
  } as CreateLlmInferenceInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountChatContext,
    TAccountInference,
    TAccountSystemProgram
  >);
}

export type CreateLlmInferenceInput<
  TAccountUser extends string = string,
  TAccountChatContext extends string = string,
  TAccountInference extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  chatContext: Address<TAccountChatContext>;
  inference: Address<TAccountInference>;
  systemProgram?: Address<TAccountSystemProgram>;
  text: CreateLlmInferenceInstructionDataArgs["text"];
  callbackProgramId: CreateLlmInferenceInstructionDataArgs["callbackProgramId"];
  callbackDiscriminator: CreateLlmInferenceInstructionDataArgs["callbackDiscriminator"];
  accountMetas: CreateLlmInferenceInstructionDataArgs["accountMetas"];
};

export function getCreateLlmInferenceInstruction<
  TAccountUser extends string,
  TAccountChatContext extends string,
  TAccountInference extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof SOLANA_LLM_ORACLE_PROGRAM_ADDRESS,
>(
  input: CreateLlmInferenceInput<
    TAccountUser,
    TAccountChatContext,
    TAccountInference,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): CreateLlmInferenceInstruction<
  TProgramAddress,
  TAccountUser,
  TAccountChatContext,
  TAccountInference,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress =
    config?.programAddress ?? SOLANA_LLM_ORACLE_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    chatContext: { value: input.chatContext ?? null, isWritable: false },
    inference: { value: input.inference ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.chatContext),
      getAccountMeta(accounts.inference),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCreateLlmInferenceInstructionDataEncoder().encode(
      args as CreateLlmInferenceInstructionDataArgs,
    ),
    programAddress,
  } as CreateLlmInferenceInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountChatContext,
    TAccountInference,
    TAccountSystemProgram
  >);
}

export type ParsedCreateLlmInferenceInstruction<
  TProgram extends string = typeof SOLANA_LLM_ORACLE_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    user: TAccountMetas[0];
    chatContext: TAccountMetas[1];
    inference: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
  };
  data: CreateLlmInferenceInstructionData;
};

export function parseCreateLlmInferenceInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCreateLlmInferenceInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      user: getNextAccount(),
      chatContext: getNextAccount(),
      inference: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getCreateLlmInferenceInstructionDataDecoder().decode(
      instruction.data,
    ),
  };
}
