/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getU8Decoder,
  getU8Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { CHAT_AGENT_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const AI_INFERENCE_DISCRIMINATOR = new Uint8Array([
  139, 217, 84, 45, 253, 148, 169, 10,
]);

export function getAiInferenceDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    AI_INFERENCE_DISCRIMINATOR,
  );
}

export type AiInferenceInstruction<
  TProgram extends string = typeof CHAT_AGENT_PROGRAM_ADDRESS,
  TAccountUser extends string | AccountMeta<string> = string,
  TAccountChatContext extends string | AccountMeta<string> = string,
  TAccountInference extends string | AccountMeta<string> = string,
  TAccountResponse extends string | AccountMeta<string> = string,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountOracleProgram extends string | AccountMeta<string> =
    "LLM4VF4uxgbcrUdwF9rBh7MUEypURp8FurEdZLhZqed",
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountUser extends string
        ? WritableSignerAccount<TAccountUser> & AccountSignerMeta<TAccountUser>
        : TAccountUser,
      TAccountChatContext extends string
        ? ReadonlyAccount<TAccountChatContext>
        : TAccountChatContext,
      TAccountInference extends string
        ? WritableAccount<TAccountInference>
        : TAccountInference,
      TAccountResponse extends string
        ? WritableAccount<TAccountResponse>
        : TAccountResponse,
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountOracleProgram extends string
        ? ReadonlyAccount<TAccountOracleProgram>
        : TAccountOracleProgram,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type AiInferenceInstructionData = {
  discriminator: ReadonlyUint8Array;
  text: string;
  seed: number;
};

export type AiInferenceInstructionDataArgs = { text: string; seed: number };

export function getAiInferenceInstructionDataEncoder(): Encoder<AiInferenceInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["text", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
      ["seed", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: AI_INFERENCE_DISCRIMINATOR }),
  );
}

export function getAiInferenceInstructionDataDecoder(): Decoder<AiInferenceInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["text", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
    ["seed", getU8Decoder()],
  ]);
}

export function getAiInferenceInstructionDataCodec(): Codec<
  AiInferenceInstructionDataArgs,
  AiInferenceInstructionData
> {
  return combineCodec(
    getAiInferenceInstructionDataEncoder(),
    getAiInferenceInstructionDataDecoder(),
  );
}

export type AiInferenceAsyncInput<
  TAccountUser extends string = string,
  TAccountChatContext extends string = string,
  TAccountInference extends string = string,
  TAccountResponse extends string = string,
  TAccountVault extends string = string,
  TAccountOracleProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  chatContext: Address<TAccountChatContext>;
  inference: Address<TAccountInference>;
  response?: Address<TAccountResponse>;
  vault?: Address<TAccountVault>;
  oracleProgram?: Address<TAccountOracleProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  text: AiInferenceInstructionDataArgs["text"];
  seed: AiInferenceInstructionDataArgs["seed"];
};

export async function getAiInferenceInstructionAsync<
  TAccountUser extends string,
  TAccountChatContext extends string,
  TAccountInference extends string,
  TAccountResponse extends string,
  TAccountVault extends string,
  TAccountOracleProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof CHAT_AGENT_PROGRAM_ADDRESS,
>(
  input: AiInferenceAsyncInput<
    TAccountUser,
    TAccountChatContext,
    TAccountInference,
    TAccountResponse,
    TAccountVault,
    TAccountOracleProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  AiInferenceInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountChatContext,
    TAccountInference,
    TAccountResponse,
    TAccountVault,
    TAccountOracleProgram,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? CHAT_AGENT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    chatContext: { value: input.chatContext ?? null, isWritable: false },
    inference: { value: input.inference ?? null, isWritable: true },
    response: { value: input.response ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
    oracleProgram: { value: input.oracleProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.response.value) {
    accounts.response.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(
          new Uint8Array([114, 101, 115, 112, 111, 110, 115, 101]),
        ),
        getAddressEncoder().encode(expectAddress(accounts.user.value)),
      ],
    });
  }
  if (!accounts.vault.value) {
    accounts.vault.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([118, 97, 117, 108, 116])),
        getAddressEncoder().encode(expectAddress(accounts.response.value)),
      ],
    });
  }
  if (!accounts.oracleProgram.value) {
    accounts.oracleProgram.value =
      "LLM4VF4uxgbcrUdwF9rBh7MUEypURp8FurEdZLhZqed" as Address<"LLM4VF4uxgbcrUdwF9rBh7MUEypURp8FurEdZLhZqed">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.chatContext),
      getAccountMeta(accounts.inference),
      getAccountMeta(accounts.response),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.oracleProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getAiInferenceInstructionDataEncoder().encode(
      args as AiInferenceInstructionDataArgs,
    ),
    programAddress,
  } as AiInferenceInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountChatContext,
    TAccountInference,
    TAccountResponse,
    TAccountVault,
    TAccountOracleProgram,
    TAccountSystemProgram
  >);
}

export type AiInferenceInput<
  TAccountUser extends string = string,
  TAccountChatContext extends string = string,
  TAccountInference extends string = string,
  TAccountResponse extends string = string,
  TAccountVault extends string = string,
  TAccountOracleProgram extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  user: TransactionSigner<TAccountUser>;
  chatContext: Address<TAccountChatContext>;
  inference: Address<TAccountInference>;
  response: Address<TAccountResponse>;
  vault: Address<TAccountVault>;
  oracleProgram?: Address<TAccountOracleProgram>;
  systemProgram?: Address<TAccountSystemProgram>;
  text: AiInferenceInstructionDataArgs["text"];
  seed: AiInferenceInstructionDataArgs["seed"];
};

export function getAiInferenceInstruction<
  TAccountUser extends string,
  TAccountChatContext extends string,
  TAccountInference extends string,
  TAccountResponse extends string,
  TAccountVault extends string,
  TAccountOracleProgram extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof CHAT_AGENT_PROGRAM_ADDRESS,
>(
  input: AiInferenceInput<
    TAccountUser,
    TAccountChatContext,
    TAccountInference,
    TAccountResponse,
    TAccountVault,
    TAccountOracleProgram,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): AiInferenceInstruction<
  TProgramAddress,
  TAccountUser,
  TAccountChatContext,
  TAccountInference,
  TAccountResponse,
  TAccountVault,
  TAccountOracleProgram,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? CHAT_AGENT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    user: { value: input.user ?? null, isWritable: true },
    chatContext: { value: input.chatContext ?? null, isWritable: false },
    inference: { value: input.inference ?? null, isWritable: true },
    response: { value: input.response ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
    oracleProgram: { value: input.oracleProgram ?? null, isWritable: false },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.oracleProgram.value) {
    accounts.oracleProgram.value =
      "LLM4VF4uxgbcrUdwF9rBh7MUEypURp8FurEdZLhZqed" as Address<"LLM4VF4uxgbcrUdwF9rBh7MUEypURp8FurEdZLhZqed">;
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.user),
      getAccountMeta(accounts.chatContext),
      getAccountMeta(accounts.inference),
      getAccountMeta(accounts.response),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.oracleProgram),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getAiInferenceInstructionDataEncoder().encode(
      args as AiInferenceInstructionDataArgs,
    ),
    programAddress,
  } as AiInferenceInstruction<
    TProgramAddress,
    TAccountUser,
    TAccountChatContext,
    TAccountInference,
    TAccountResponse,
    TAccountVault,
    TAccountOracleProgram,
    TAccountSystemProgram
  >);
}

export type ParsedAiInferenceInstruction<
  TProgram extends string = typeof CHAT_AGENT_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    user: TAccountMetas[0];
    chatContext: TAccountMetas[1];
    inference: TAccountMetas[2];
    response: TAccountMetas[3];
    vault: TAccountMetas[4];
    oracleProgram: TAccountMetas[5];
    systemProgram: TAccountMetas[6];
  };
  data: AiInferenceInstructionData;
};

export function parseAiInferenceInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedAiInferenceInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      user: getNextAccount(),
      chatContext: getNextAccount(),
      inference: getNextAccount(),
      response: getNextAccount(),
      vault: getNextAccount(),
      oracleProgram: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getAiInferenceInstructionDataDecoder().decode(instruction.data),
  };
}
