/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  addDecoderSizePrefix,
  addEncoderSizePrefix,
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU32Decoder,
  getU32Encoder,
  getUtf8Decoder,
  getUtf8Encoder,
  transformEncoder,
  type AccountMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type WritableAccount,
} from "@solana/kit";
import { CHAT_AGENT_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const CALLBACK_FROM_AI_DISCRIMINATOR = new Uint8Array([
  153, 28, 39, 253, 98, 30, 162, 68,
]);

export function getCallbackFromAiDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    CALLBACK_FROM_AI_DISCRIMINATOR,
  );
}

export type CallbackFromAiInstruction<
  TProgram extends string = typeof CHAT_AGENT_PROGRAM_ADDRESS,
  TAccountIdentity extends string | AccountMeta<string> = string,
  TAccountResponse extends string | AccountMeta<string> = string,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountIdentity extends string
        ? ReadonlyAccount<TAccountIdentity>
        : TAccountIdentity,
      TAccountResponse extends string
        ? WritableAccount<TAccountResponse>
        : TAccountResponse,
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CallbackFromAiInstructionData = {
  discriminator: ReadonlyUint8Array;
  response: string;
};

export type CallbackFromAiInstructionDataArgs = { response: string };

export function getCallbackFromAiInstructionDataEncoder(): Encoder<CallbackFromAiInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["response", addEncoderSizePrefix(getUtf8Encoder(), getU32Encoder())],
    ]),
    (value) => ({ ...value, discriminator: CALLBACK_FROM_AI_DISCRIMINATOR }),
  );
}

export function getCallbackFromAiInstructionDataDecoder(): Decoder<CallbackFromAiInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["response", addDecoderSizePrefix(getUtf8Decoder(), getU32Decoder())],
  ]);
}

export function getCallbackFromAiInstructionDataCodec(): Codec<
  CallbackFromAiInstructionDataArgs,
  CallbackFromAiInstructionData
> {
  return combineCodec(
    getCallbackFromAiInstructionDataEncoder(),
    getCallbackFromAiInstructionDataDecoder(),
  );
}

export type CallbackFromAiAsyncInput<
  TAccountIdentity extends string = string,
  TAccountResponse extends string = string,
  TAccountVault extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  identity: Address<TAccountIdentity>;
  response: Address<TAccountResponse>;
  vault?: Address<TAccountVault>;
  systemProgram?: Address<TAccountSystemProgram>;
  responseArg: CallbackFromAiInstructionDataArgs["response"];
};

export async function getCallbackFromAiInstructionAsync<
  TAccountIdentity extends string,
  TAccountResponse extends string,
  TAccountVault extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof CHAT_AGENT_PROGRAM_ADDRESS,
>(
  input: CallbackFromAiAsyncInput<
    TAccountIdentity,
    TAccountResponse,
    TAccountVault,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  CallbackFromAiInstruction<
    TProgramAddress,
    TAccountIdentity,
    TAccountResponse,
    TAccountVault,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? CHAT_AGENT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    identity: { value: input.identity ?? null, isWritable: false },
    response: { value: input.response ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input, response: input.responseArg };

  // Resolve default values.
  if (!accounts.vault.value) {
    accounts.vault.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([118, 97, 117, 108, 116])),
        getAddressEncoder().encode(expectAddress(accounts.response.value)),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.identity),
      getAccountMeta(accounts.response),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCallbackFromAiInstructionDataEncoder().encode(
      args as CallbackFromAiInstructionDataArgs,
    ),
    programAddress,
  } as CallbackFromAiInstruction<
    TProgramAddress,
    TAccountIdentity,
    TAccountResponse,
    TAccountVault,
    TAccountSystemProgram
  >);
}

export type CallbackFromAiInput<
  TAccountIdentity extends string = string,
  TAccountResponse extends string = string,
  TAccountVault extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  identity: Address<TAccountIdentity>;
  response: Address<TAccountResponse>;
  vault: Address<TAccountVault>;
  systemProgram?: Address<TAccountSystemProgram>;
  responseArg: CallbackFromAiInstructionDataArgs["response"];
};

export function getCallbackFromAiInstruction<
  TAccountIdentity extends string,
  TAccountResponse extends string,
  TAccountVault extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof CHAT_AGENT_PROGRAM_ADDRESS,
>(
  input: CallbackFromAiInput<
    TAccountIdentity,
    TAccountResponse,
    TAccountVault,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): CallbackFromAiInstruction<
  TProgramAddress,
  TAccountIdentity,
  TAccountResponse,
  TAccountVault,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? CHAT_AGENT_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    identity: { value: input.identity ?? null, isWritable: false },
    response: { value: input.response ?? null, isWritable: true },
    vault: { value: input.vault ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input, response: input.responseArg };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.identity),
      getAccountMeta(accounts.response),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCallbackFromAiInstructionDataEncoder().encode(
      args as CallbackFromAiInstructionDataArgs,
    ),
    programAddress,
  } as CallbackFromAiInstruction<
    TProgramAddress,
    TAccountIdentity,
    TAccountResponse,
    TAccountVault,
    TAccountSystemProgram
  >);
}

export type ParsedCallbackFromAiInstruction<
  TProgram extends string = typeof CHAT_AGENT_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    identity: TAccountMetas[0];
    response: TAccountMetas[1];
    vault: TAccountMetas[2];
    systemProgram: TAccountMetas[3];
  };
  data: CallbackFromAiInstructionData;
};

export function parseCallbackFromAiInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCallbackFromAiInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 4) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      identity: getNextAccount(),
      response: getNextAccount(),
      vault: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getCallbackFromAiInstructionDataDecoder().decode(instruction.data),
  };
}
