/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from "@solana/kit";
import { SOLANA_LLM_ORACLE_PROGRAM_ADDRESS } from "../programs";

/** InvalidAdmin: You're not an admin ser! */
export const SOLANA_LLM_ORACLE_ERROR__INVALID_ADMIN = 0x1770; // 6000

export type SolanaLlmOracleError =
  typeof SOLANA_LLM_ORACLE_ERROR__INVALID_ADMIN;

let solanaLlmOracleErrorMessages:
  | Record<SolanaLlmOracleError, string>
  | undefined;
if (process.env.NODE_ENV !== "production") {
  solanaLlmOracleErrorMessages = {
    [SOLANA_LLM_ORACLE_ERROR__INVALID_ADMIN]: `You're not an admin ser!`,
  };
}

export function getSolanaLlmOracleErrorMessage(
  code: SolanaLlmOracleError,
): string {
  if (process.env.NODE_ENV !== "production") {
    return (
      solanaLlmOracleErrorMessages as Record<SolanaLlmOracleError, string>
    )[code];
  }

  return "Error message not available in production bundles.";
}

export function isSolanaLlmOracleError<
  TProgramErrorCode extends SolanaLlmOracleError,
>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode,
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    SOLANA_LLM_ORACLE_PROGRAM_ADDRESS,
    code,
  );
}
